# Site settings
title: moong2's portfolio 
email: pushclap@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "portfolio" # the subpath of your site, e.g. /blog/
url: "portfolio" # the base hostname & protocol for your site

github_username: moong2
velog_username : moong2

# Build settings
markdown: kramdown
